/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { LessonService } from "../lesson.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { LessonCreateInput } from "./LessonCreateInput";
import { Lesson } from "./Lesson";
import { LessonFindManyArgs } from "./LessonFindManyArgs";
import { LessonWhereUniqueInput } from "./LessonWhereUniqueInput";
import { LessonUpdateInput } from "./LessonUpdateInput";
import { ExerciseFindManyArgs } from "../../exercise/base/ExerciseFindManyArgs";
import { Exercise } from "../../exercise/base/Exercise";
import { ExerciseWhereUniqueInput } from "../../exercise/base/ExerciseWhereUniqueInput";
import { SubmitExerciseInput } from "../../exercise/SubmitExerciseInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class LessonControllerBase {
  constructor(
    protected readonly service: LessonService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Lesson })
  @nestAccessControl.UseRoles({
    resource: "Lesson",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createLesson(@common.Body() data: LessonCreateInput): Promise<Lesson> {
    return await this.service.createLesson({
      data: {
        ...data,

        course: data.course
          ? {
              connect: data.course,
            }
          : undefined,
      },
      select: {
        content: true,

        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        order: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Lesson] })
  @ApiNestedQuery(LessonFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Lesson",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async lessons(@common.Req() request: Request): Promise<Lesson[]> {
    const args = plainToClass(LessonFindManyArgs, request.query);
    return this.service.lessons({
      ...args,
      select: {
        content: true,

        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        order: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Lesson })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Lesson",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async lesson(
    @common.Param() params: LessonWhereUniqueInput
  ): Promise<Lesson | null> {
    const result = await this.service.lesson({
      where: params,
      select: {
        content: true,

        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        order: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Lesson })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Lesson",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateLesson(
    @common.Param() params: LessonWhereUniqueInput,
    @common.Body() data: LessonUpdateInput
  ): Promise<Lesson | null> {
    try {
      return await this.service.updateLesson({
        where: params,
        data: {
          ...data,

          course: data.course
            ? {
                connect: data.course,
              }
            : undefined,
        },
        select: {
          content: true,

          course: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          order: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Lesson })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Lesson",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteLesson(
    @common.Param() params: LessonWhereUniqueInput
  ): Promise<Lesson | null> {
    try {
      return await this.service.deleteLesson({
        where: params,
        select: {
          content: true,

          course: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          order: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/exercises")
  @ApiNestedQuery(ExerciseFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Exercise",
    action: "read",
    possession: "any",
  })
  async findExercises(
    @common.Req() request: Request,
    @common.Param() params: LessonWhereUniqueInput
  ): Promise<Exercise[]> {
    const query = plainToClass(ExerciseFindManyArgs, request.query);
    const results = await this.service.findExercises(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        difficultyLevel: true,
        id: true,
        language: true,

        lesson: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/exercises")
  @nestAccessControl.UseRoles({
    resource: "Lesson",
    action: "update",
    possession: "any",
  })
  async connectExercises(
    @common.Param() params: LessonWhereUniqueInput,
    @common.Body() body: ExerciseWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      exercises: {
        connect: body,
      },
    };
    await this.service.updateLesson({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/exercises")
  @nestAccessControl.UseRoles({
    resource: "Lesson",
    action: "update",
    possession: "any",
  })
  async updateExercises(
    @common.Param() params: LessonWhereUniqueInput,
    @common.Body() body: ExerciseWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      exercises: {
        set: body,
      },
    };
    await this.service.updateLesson({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/exercises")
  @nestAccessControl.UseRoles({
    resource: "Lesson",
    action: "update",
    possession: "any",
  })
  async disconnectExercises(
    @common.Param() params: LessonWhereUniqueInput,
    @common.Body() body: ExerciseWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      exercises: {
        disconnect: body,
      },
    };
    await this.service.updateLesson({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Post("/exercise/submit")
  @swagger.ApiOkResponse({
    type: String,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async SubmitExercise(
    @common.Body()
    body: SubmitExerciseInput
  ): Promise<string> {
    return this.service.SubmitExercise(body);
  }
}
